server:
  port: 8706
spring:
  application:
    name: openfeign-demo
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8701/eureka
