spring:
  datasource:
    url: jdbc:mysql://49.235.29.59:3301/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8083
mybatis:
#配置xml文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml


